[project]
name = "lerobot_notebook_pipeline"
version = "0.1.0"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta" 

[tool.setuptools]
packages = ["lerobot_notebook_pipeline", "lerobot_notebook_pipeline.dataset_utils"] 